### ISSUE TITLE
File format, mapping and naming conventions

### ISSUE THREAD

**Issue by pgaglani1** [IBM-Cloud/gp-jenkins#3]
- Map source files with spaces to bundleid replacing space to "_".
- Truncate source suffix from target resource files
e.g
xxx_en.json - given "en" is source language
xxx_en-map.json - given {"en":"en-map", .. } in Language Mapping
will truncate "_en" and "_en-map" respectively from target resource file during download
- Update docs referring to Bluemix with IBM Cloud.
- Support exporting resources to <lang>.<file extension>
Some JavaScript library uses .json to store localized resource, for example, French localization in fr.json

**Comment by pgaglani1** [comment]
[PR](https://github.com/IBM-Cloud/gp-jenkins/pull/4)

**Comment by srl295** [comment]
Landed in 2cb76bc
